server:
  port: 9100

spring:
  application:
    name: Employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: manash1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
